from sqlmodel import Session, select
from backend.database import engine
from backend.models import Track, GeneratedPlaylist
from backend.services.sequencer import extract_energy_curve
import spotipy
import json

SECTION_PROFILES = {
    "centering": {
        "energy": (0.1, 0.3),
        "tempo": (50, 70),
        "acousticness": (0.6, 1.0),
        "instrumentalness": (0.7, 1.0),
    },
    "warmup": {
        "energy": (0.3, 0.5),
        "tempo": (70, 90),
        "acousticness": (0.4, 1.0),
        "instrumentalness": (0.5, 1.0),
    },
    "warm_up": {
        "energy": (0.3, 0.5),
        "tempo": (70, 90),
        "acousticness": (0.4, 1.0),
        "instrumentalness": (0.5, 1.0),
    },
    "sun_salutations": {"energy": (0.5, 0.7), "tempo": (90, 110), "instrumentalness": (0.3, 1.0)},
    "standing": {"energy": (0.5, 0.75), "tempo": (85, 115)},
    "peak": {"energy": (0.7, 0.95), "tempo": (100, 130)},
    "floor": {"energy": (0.3, 0.5), "tempo": (70, 95), "acousticness": (0.4, 1.0)},
    "cooldown": {"energy": (0.2, 0.45), "tempo": (60, 85), "acousticness": (0.5, 1.0)},
    "cool_down": {"energy": (0.2, 0.45), "tempo": (60, 85), "acousticness": (0.5, 1.0)},
    "savasana": {
        "energy": (0.0, 0.2),
        "tempo": (40, 70),
        "acousticness": (0.7, 1.0),
        "instrumentalness": (0.8, 1.0),
    },
}


def get_spotify_client() -> spotipy.Spotify | None:
    # Delegates to backend.routers.spotify.get_valid_spotify_client (token-refresh aware).
    # Lazy import avoids circular dependency with backend.routers.spotify.
    from backend.routers.spotify import get_valid_spotify_client

    with Session(engine) as session:
        return get_valid_spotify_client(session)


def find_tracks_for_section(section_label: str, duration_ms: int, exclude_ids: set) -> list[Track]:
    label_key = section_label.lower().replace(" ", "_")
    profile = SECTION_PROFILES.get(label_key, {"energy": (0.3, 0.7), "tempo": (70, 110)})
    with Session(engine) as session:
        stmt = select(Track)
        tracks = session.exec(stmt).all()
    matching = []
    for t in tracks:
        if t.track_id in exclude_ids:
            continue
        if t.energy is not None:
            e_min, e_max = profile.get("energy", (0, 1))
            if not (e_min <= t.energy <= e_max):
                continue
        if t.tempo is not None and "tempo" in profile:
            t_min, t_max = profile["tempo"]
            if not (t_min <= t.tempo <= t_max):
                continue
        if t.acousticness is not None and "acousticness" in profile:
            a_min, a_max = profile["acousticness"]
            if not (a_min <= t.acousticness <= a_max):
                continue
        if t.instrumentalness is not None and "instrumentalness" in profile:
            i_min, i_max = profile["instrumentalness"]
            if not (i_min <= t.instrumentalness <= i_max):
                continue
        matching.append(t)
    matching.sort(key=lambda x: x.popularity or 0, reverse=True)
    selected = []
    total_ms = 0
    for t in matching:
        if total_ms >= duration_ms:
            break
        selected.append(t)
        total_ms += t.duration_ms
        exclude_ids.add(t.track_id)
    return selected


def generate_playlist_for_flow(
    flow_name: str, blocks_json: str, flow_version_id: str = None
) -> dict | None:
    sp = get_spotify_client()
    if not sp:
        return None
    try:
        sections = json.loads(blocks_json)
    except (ValueError, TypeError):
        return None
    all_tracks = []
    used_ids = set()
    for section in sections:
        label = section.get("label", "flow")
        section_duration_ms = sum(b.get("duration", 30) * 1000 for b in section.get("blocks", []))
        tracks = find_tracks_for_section(label, section_duration_ms, used_ids)
        all_tracks.extend(tracks)
    if not all_tracks:
        return None
    user = sp.current_user()
    playlist = sp.user_playlist_create(
        user["id"],
        f"\U0001f9d8 {flow_name}",
        public=False,
        description="Generated by Digital Sangha",
    )
    track_uris = [t.spotify_uri for t in all_tracks if t.spotify_uri]
    if track_uris:
        for i in range(0, len(track_uris), 100):
            sp.playlist_add_items(playlist["id"], track_uris[i : i + 100])
    with Session(engine) as session:
        gen = GeneratedPlaylist(
            playlist_id=playlist["id"],
            flow_version_id=flow_version_id,
            name=playlist["name"],
            spotify_url=playlist["external_urls"]["spotify"],
            track_ids=json.dumps([t.track_id for t in all_tracks]),
            total_duration_ms=sum(t.duration_ms for t in all_tracks),
        )
        session.add(gen)
        session.commit()
    return {
        "playlist_id": playlist["id"],
        "url": playlist["external_urls"]["spotify"],
        "name": playlist["name"],
        "track_count": len(all_tracks),
    }


def has_tracks() -> bool:
    with Session(engine) as session:
        count = session.exec(select(Track)).first()
        return count is not None
